//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace SGTO.UI.Webforms.Pages.CoberturasPlanes
{


    public partial class NuevaCobertura
    {

        /// <summary>
        /// CoberturasFormControl control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SGTO.UI.Webforms.Controles.Coberturas.CoberturasForm CoberturasFormControl;
    }
}
