//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace SGTO.UI.Webforms.Pages.Reportes
{


    public partial class Reportes
    {

        /// <summary>
        /// reporteTurnosControl control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SGTO.UI.Webforms.Controles.Reportes.Turnos.ReporteTurnos reporteTurnosControl;

        /// <summary>
        /// reportePacientesControl control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SGTO.UI.Webforms.Controles.Reportes.Pacientes.ReportePacientes reportePacientesControl;
    }
}
